---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thang-APP_NAME-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thang-APP_NAME
  template:
    metadata:
      labels:
        app: thang-APP_NAME
    spec:
      containers:
        - name: thang-APP_NAME
          image: letanthang/APP_NAME
          ports:
            - containerPort: 80
              name: web
          envFrom:
            - configMapRef:
                name: thang-staging-config
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "75Mi"
              cpu: "75m"
---

