apiVersion: v1
kind: Service
metadata:
  name: thang-my-framework-svc
spec:
  selector:
    app: thang-my-framework
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: goport
  type: NodePort
