---
apiVersion: v1
kind: Service
metadata:
  name: thang-APP_NAME-svc
spec:
  selector:
    app: thang-APP_NAME
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
      name: goport
  type: NodePort
---

